<?php
declare(strict_types=1);
$packageAutoload = dirname(__DIR__).'/vendor/autoload.php';
if (is_file($packageAutoload)) require $packageAutoload;
$roots=['Pam\\Native\\BackgroundTransfer\\'=>dirname(__DIR__).'/src/','Pam\\Native\\Testing\\'=>dirname(__DIR__,2).'/pam-native-testing/src/','Pam\\Native\\'=>dirname(__DIR__,2).'/../pam-native/packages/native/src/'];
spl_autoload_register(static function(string $class)use($roots):void{foreach($roots as $prefix=>$root){if(str_starts_with($class,$prefix)){$file=$root.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require$file;return;}}});
use Pam\Native\BackgroundTransfer\BackgroundTransfer;use Pam\Native\BackgroundTransfer\TransferState;use Pam\Native\Internal\Wire;use Pam\Native\Testing\NativeTestHarness;
$tests=[];$test=static function(string $n,Closure $f)use(&$tests):void{$tests[$n]=$f;};
$test('enqueues typed durable download',static function():void{$fake=NativeTestHarness::install();$fake->succeed('background-transfer','enqueue',['identifier'=>'550e8400-e29b-41d4-a716-446655440000']);$id=null;(new BackgroundTransfer())->download('https://cdn.example.test/video.mp4','media/video.mp4',static function(?string $value)use(&$id):void{$id=$value;});if($id!=='550e8400-e29b-41d4-a716-446655440000')throw new RuntimeException('identifier mismatch');$call=$fake->lastCall();$payload=$call?Wire::decodeMap($call->payload):[];if(($payload['kind']??null)!==1||($payload['network']??null)!==1)throw new RuntimeException('integer enum contract mismatch');$fake->assertSatisfied();NativeTestHarness::uninstall();});
$test('maps native status',static function():void{$fake=NativeTestHarness::install();$fake->succeed('background-transfer','status',['identifier'=>'id','kind'=>2,'state'=>2,'bytesTransferred'=>512,'bytesTotal'=>1024]);$snapshot=null;(new BackgroundTransfer())->status('id',static function($v)use(&$snapshot):void{$snapshot=$v;});if($snapshot?->state!==TransferState::Running||$snapshot->bytesTransferred!==512)throw new RuntimeException('snapshot mismatch');NativeTestHarness::uninstall();});
$test('rejects insecure URLs before bridge',static function():void{try{(new BackgroundTransfer())->download('http://example.test/a','a',static function():void{});throw new RuntimeException('accepted HTTP');}catch(InvalidArgumentException){}});
$failed=0;foreach($tests as $name=>$run){try{$run();fwrite(STDOUT,"PASS $name\n");}catch(Throwable $e){$failed++;fwrite(STDERR,"FAIL $name: {$e->getMessage()}\n");}}fwrite(STDOUT,count($tests)." tests, $failed failures\n");exit($failed?1:0);
